<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="EN32276" name="com.github.fge.jsonschema.processors.validation.ValidationProcessorTest" tests="4" failures="0" timestamp="08 Nov 2017 19:10:15 GMT" time="0.060" errors="0">
  <testcase name="childrenAreExploredOnDemandEvenIfContainerFails" time="0.035" classname="com.github.fge.jsonschema.processors.validation.ValidationProcessorTest"/>
  <testcase name="circularReferencingDuringValidationIsDetected" time="0.012" classname="com.github.fge.jsonschema.processors.validation.ValidationProcessorTest"/>
  <testcase name="childrenAreNotExploredByDefaultIfContainerFails" time="0.005" classname="com.github.fge.jsonschema.processors.validation.ValidationProcessorTest"/>
  <testcase name="enteringSamePointerWithDifferentPathsDoesNotThrowException" time="0.008" classname="com.github.fge.jsonschema.processors.validation.ValidationProcessorTest"/>
</testsuite> <!-- com.github.fge.jsonschema.processors.validation.ValidationProcessorTest -->
